### ISSUE TITLE
Texture

### ISSUE THREAD

**Issue by Cronyzz** [djhaled/Uiana-MapImporter#10]
My Texture is not importing properly. please help me
![Screenshot 2023-07-07 073307](https://github.com/djhaled/Uiana-MapImporter/assets/127186075/4b001e84-3f2a-45a1-94fa-38c712568d9a)

**Comment by AMMAREN** [comment]
Also the same here with V1.08
it seem the master material is not load correctly

![Kasbah](https://github.com/djhaled/Uiana-MapImporter/assets/7099115/934e7e6d-b7fb-45f3-907d-ba79a8eabb77)

**Comment by KaiserM21** [comment]
whats your unreal engine version?

**Comment by AMMAREN** [comment]
5.1

**Comment by Cronyzz** [comment]
Ya my to 5.1.1

**Comment by djhaled** [comment]
If you guys can test out latest commit might have fixed it.

**Comment by AMMAREN** [comment]
still not work

**Comment by RETROXD** [comment]
![image](https://github.com/djhaled/Uiana-MapImporter/assets/50623910/57c77af3-5a56-42fd-9e3a-69657b6f6a5b)
I seem to be having a similar issue, UE v5.1.1 also
I have not tried other engine versions as I need to use a specific version
I also tested that "fix <5.2" commit and no luck

It isn't loading some textures as well as it's adding in all the unused greybox meshes

**Comment by djhaled** [comment]
Are all the issues on 5.1.1?

**Comment by KaiserM21** [comment]
Should work now on 5.1.1, release is updated with materials compiled on that version 👍
