### ISSUE TITLE
Unreal crash when importing Jet psk

### ISSUE THREAD

**Issue by BTipold** [djhaled/Uiana-MapImporter#11]
Assertion failed: (Index >= 0) & (Index < ArrayNum) [File:C:\Program Files\Epic Games\UE_5.2\Engine\Source\Runtime\Core\Public\Containers\Array.h] [Line: 752] Array index out of bounds: 2489600 from an array of size 14627

UnrealEditor_UnrealPSKPSA!UPSKFactory::Import() [D:\Documents\Unreal Projects\Valorant\Plugins\UnrealPSKPSA\Source\UnrealPSKPSA\Private\PSKFactory.cpp:67]
UnrealEditor_UnrealPSKPSA!UPSKFactory::FactoryCreateFile() [D:\Documents\Unreal Projects\Valorant\Plugins\UnrealPSKPSA\Source\UnrealPSKPSA\Public\PSKFactory.h:43]
UnrealEditor_UnrealEd
UnrealEditor_AssetTools
UnrealEditor_AssetTools
UnrealEditor_AssetTools
UnrealEditor_AssetTools
UnrealEditor_ContentBrowserAssetDataSource
UnrealEditor_ContentBrowserAssetDataSource
UnrealEditor_ContentBrowserAssetDataSource
UnrealEditor_ContentBrowserAssetDataSource
UnrealEditor_ContentBrowserAssetDataSource
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_ApplicationCore
UnrealEditor_ApplicationCore
UnrealEditor_ApplicationCore
UnrealEditor_ApplicationCore
user32
user32
UnrealEditor_ApplicationCore
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
kernel32
ntdll

Versions:
Unreal 5.2.1
VS 2022 Version 17.7.1

Additional information:
i'm attaching a log file called "valorant.txt". I found it in saved/logs and it looks like it might contain additional callstack information:
[Valorant.log](https://github.com/djhaled/Uiana-MapImporter/files/12387082/Valorant.log)

**Comment by BTipold** [comment]
Hoping its user error 🤞

**Comment by djhaled** [comment]
This is not a PSK/PSA importer.
Use the actual PSK/PSA importer: https://github.com/KaiserM21/UnrealPSKPSA.

**Comment by BTipold** [comment]
Hey sorry, to clarify, did you mean USE the PSK PSA importer (like use that plugin?) or file the issue on that github?

**Comment by KaiserM21** [comment]
> Hey sorry, to clarify, did you mean USE the PSK PSA importer (like use that plugin?) or file the issue on that github?

The addon in this repo does not work outside of importing map meshes. This is the link to the PSK/PSA importer: https://github.com/KaiserM21/UnrealPSKPSA. Currently there are crashes with animation import in Unreal 5.2.1+, will fix when I have time.

**Comment by BTipold** [comment]
Thanks for clarifying.

**Comment by KaiserM21** [comment]
UnrealPSKPSA is fixed now fyi👍
