### ISSUE TITLE
5.3 Support

### ISSUE THREAD

**Issue by iamameme** [djhaled/Uiana-MapImporter#12]
Hello! More a request than an issue but, I've got the Plugin running in 5.3 and imported a map, but seeing some texture issues. Any idea why this is?

To note, this was a fresh 5.3 project / fresh 5.3 engine install which imported Fracture.

Thanks!

![auxillary](https://github.com/djhaled/Uiana-MapImporter/assets/5202089/578dc9b1-8bde-4b8c-8664-75b668d301db)

**Comment by KaiserM21** [comment]
Window-Levels
Disable Blockout/Greybox and other unwanted levels.
