### ISSUE TITLE
Compilation Error: UE 5.3.2

### ISSUE THREAD

**Issue by mungaihehe** [djhaled/Uiana-MapImporter#14]
Registered process C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\Win64\UnrealEditor.exe (PID: 12896)
Loading module C:\Users\_________\Documents\Unreal Projects\HelloValorant2\Binaries\Win64\UnrealEditor-HelloValorant2.dll (0.049 MB)
Loaded 1 module(s), 671 lazy load module(s), and 355 reserved page ranges (0.000s, 2 translation units)
Live coding ready - Save changes and press Ctrl+Alt+F11 to re-compile code
Manual recompile triggered
---------- Creating patch ----------
Running C:\Program Files\Epic Games\UE_5.3\Engine\Build\BatchFiles\Build.bat -Target="HelloValorant2Editor Win64 Development -Project=""C:/Users/_____/Documents/Unreal Projects/HelloValorant2/HelloValorant2.uproject""" -LiveCoding -LiveCodingModules="C:/Program Files/Epic Games/UE_5.3/Engine/Intermediate/LiveCodingModules.json" -LiveCodingManifest="C:/Program Files/Epic Games/UE_5.3/Engine/Intermediate/LiveCoding.json" -WaitMutex -LiveCodingLimit=100
Quick restart disabled when re-instancing is enabled.
  Using bundled DotNet SDK version: 6.0.302
  Running UnrealBuildTool: dotnet "..\..\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" -Target="HelloValorant2Editor Win64 Development -Project=""C:/Users/_________/Documents/Unreal Projects/HelloValorant2/HelloValorant2.uproject""" -LiveCoding -LiveCodingModules="C:/Program Files/Epic Games/UE_5.3/Engine/Intermediate/LiveCodingModules.json" -LiveCodingManifest="C:/Program Files/Epic Games/UE_5.3/Engine/Intermediate/LiveCoding.json" -WaitMutex -LiveCodingLimit=100
  Log file: C:\Users\_________\AppData\Local\UnrealBuildTool\Log.txt
  Creating makefile for HelloValorant2Editor (no existing makefile)
  Warning: Plugin 'Uiana' does not list plugin 'PythonScriptPlugin' as a dependency, but module 'Uiana' depends on 'PythonScriptPlugin'.
  Warning: Plugin 'UnrealPSKPSA' does not list plugin 'ProceduralMeshComponent' as a dependency, but module 'UnrealPSKPSA' depends on 'ProceduralMeshComponent'.
  Warning: Plugin 'UnrealPSKPSA' does not list plugin 'EditorScriptingUtilities' as a dependency, but module 'UnrealPSKPSA' depends on 'EditorScriptingUtilities'.
  Parsing headers for HelloValorant2Editor
    Running Internal UnrealHeaderTool "C:\Users\_________\Documents\Unreal Projects\HelloValorant2\HelloValorant2.uproject" "C:\Users\_________\Documents\Unreal Projects\HelloValorant2\Intermediate\Build\Win64\HelloValorant2Editor\Development\HelloValorant2Editor.uhtmanifest" -WarningsAsErrors -installed
  Total of 16 written
  Reflection code generated for HelloValorant2Editor in 7.8039853 seconds
  Building HelloValorant2Editor...
  Using Visual Studio 2022 14.38.33133 toolchain (C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130) and Windows 10.0.22621.0 SDK (C:\Program Files (x86)\Windows Kits\10).
  Determining max actions to execute in parallel (2 physical cores, 4 logical cores)
    Executing up to 2 processes, one per physical core
  ------ Building 3 action(s) started ------
  [1/3] Compile [x64] SharedPCH.UnrealEd.Cpp20.cpp
  [2/3] Compile [x64] Module.UnrealPSKPSA.cpp
  C:\Users\_______\Documents\Unreal Projects\HelloValorant2\Plugins\UnrealPSKPSA\Source\UnrealPSKPSA\Private\BPFL.cpp(249): error C2660: 'CreatePackage': function does not take 2 arguments
  C:\Program Files\Epic Games\UE_5.3\Engine\Source\Runtime\CoreUObject\Public\UObject\UObjectGlobals.h(948): note: see declaration of 'CreatePackage'
  C:\Users\______\Documents\Unreal Projects\HelloValorant2\Plugins\UnrealPSKPSA\Source\UnrealPSKPSA\Private\BPFL.cpp(249): note: while trying to match the argument list '(nullptr, const TCHAR *)'
  C:\Users\_______\Documents\Unreal Projects\HelloValorant2\Plugins\UnrealPSKPSA\Source\UnrealPSKPSA\Private\PSAFactory.cpp(67): error C2065: 'FComponentReregisterContext': undeclared identifier
  C:\Users\________\Documents\Unreal Projects\HelloValorant2\Plugins\UnrealPSKPSA\Source\UnrealPSKPSA\Private\PSAFactory.cpp(67): error C2146: syntax error: missing ';' before identifier 'ReregisterContext'
  C:\Users\________\Documents\Unreal Projects\HelloValorant2\Plugins\UnrealPSKPSA\Source\UnrealPSKPSA\Private\PSAFactory.cpp(67): error C3861: 'ReregisterContext': identifier not found
  C:\Users\_________\Documents\Unreal Projects\HelloValorant2\Plugins\UnrealPSKPSA\Source\UnrealPSKPSA\Private\PSAFactory.cpp(31): warning C4996: 'IAnimationDataController::SetPlayLength': SetPlayLength with length in seconds in deprecated use SetNumberOfFrames using FFrameNumber instead Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
  C:\Users\_________\Documents\Unreal Projects\HelloValorant2\Plugins\UnrealPSKPSA\Source\UnrealPSKPSA\Private\PSAFactory.cpp(55): warning C4996: 'IAnimationDataController::AddBoneTrack': AddBoneTrack returning index is deprecated use AddBoneCurve returning bool instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
  C:\Users\_________\Documents\Unreal Projects\HelloValorant2\Plugins\UnrealPSKPSA\Source\UnrealPSKPSA\Private\PSKFactory.cpp(162): error C2027: use of undefined type 'FSkeletalMeshLODInfo'
  C:\Program Files\Epic Games\UE_5.3\Engine\Source\Runtime\Engine\Classes\Engine\SkinnedAsset.h(24): note: see declaration of 'FSkeletalMeshLODInfo'
  C:\Users\_________\Documents\Unreal Projects\HelloValorant2\Plugins\UnrealPSKPSA\Source\UnrealPSKPSA\Private\PSKFactory.cpp(163): error C2027: use of undefined type 'FSkeletalMeshLODInfo'
  C:\Program Files\Epic Games\UE_5.3\Engine\Source\Runtime\Engine\Classes\Engine\SkinnedAsset.h(24): note: see declaration of 'FSkeletalMeshLODInfo'
  C:\Users\_________\Documents\Unreal Projects\HelloValorant2\Plugins\UnrealPSKPSA\Source\UnrealPSKPSA\Private\PSKFactory.cpp(164): error C2027: use of undefined type 'FSkeletalMeshLODInfo'
  C:\Program Files\Epic Games\UE_5.3\Engine\Source\Runtime\Engine\Classes\Engine\SkinnedAsset.h(24): note: see declaration of 'FSkeletalMeshLODInfo'
  C:\Users\_________\Documents\Unreal Projects\HelloValorant2\Plugins\UnrealPSKPSA\Source\UnrealPSKPSA\Private\PSKFactory.cpp(165): error C2027: use of undefined type 'FSkeletalMeshLODInfo'
  C:\Program Files\Epic Games\UE_5.3\Engine\Source\Runtime\Engine\Classes\Engine\SkinnedAsset.h(24): note: see declaration of 'FSkeletalMeshLODInfo'
  C:\Users\_________\Documents\Unreal Projects\HelloValorant2\Plugins\UnrealPSKPSA\Source\UnrealPSKPSA\Private\PSKFactory.cpp(166): error C2027: use of undefined type 'FSkeletalMeshLODInfo'
  C:\Program Files\Epic Games\UE_5.3\Engine\Source\Runtime\Engine\Classes\Engine\SkinnedAsset.h(24): note: see declaration of 'FSkeletalMeshLODInfo'
  C:\Users\_________\Documents\Unreal Projects\HelloValorant2\Plugins\UnrealPSKPSA\Source\UnrealPSKPSA\Private\PSKFactory.cpp(179): error C2027: use of undefined type 'FSkeletalMeshLODInfo'
  C:\Program Files\Epic Games\UE_5.3\Engine\Source\Runtime\Engine\Classes\Engine\SkinnedAsset.h(24): note: see declaration of 'FSkeletalMeshLODInfo'
  C:\Users\_________\Documents\Unreal Projects\HelloValorant2\Plugins\UnrealPSKPSA\Source\UnrealPSKPSA\Private\PSKFactory.cpp(192): error C2027: use of undefined type 'FSkeletalMaterial'
  C:\Program Files\Epic Games\UE_5.3\Engine\Source\Editor\UnrealEd\Public\ImportUtils\SkeletalMeshImportUtils.h(10): note: see declaration of 'FSkeletalMaterial'
  [3/3] Compile [x64] Module.Uiana.cpp
  Total time in Parallel executor: 194.73 seconds
  Total execution time: 214.36 seconds
Build failed.

**Comment by ananttheant** [comment]
Hey @mungaihehe, 

Could you please tell me the changes you did, unfortunately I'm not familiar with C++ and Unreal but I'm helping a friend to resolve this issue. 

Maybe forking the repo and doing your changes on a branch would be really helpful
