### ISSUE TITLE
Not importing

### ISSUE THREAD

**Issue by iQuizV** [djhaled/Uiana-MapImporter#4]
Everything worked until the very last part. I clicked the green generate map button, but there was nothing in the level. Nothing popped up, but in split folder which is in the map folder which is in the exports folder had a bunch of folder with nothing in them.

**Comment by iQuizV** [comment]
I also have .net 6.0.5

**Comment by Scissorlicks** [comment]
Having the same problem, how did you fix it?

**Comment by KaiserM21** [comment]
> 
make sure:
1. you have .net 6 from the link
2. your pak folder is set correctly, and your Valorant works fine (sometimes need to play a match to verify)
then: delete the export folder, and import again. It should work.
