### ISSUE TITLE
can't import meshes

### ISSUE THREAD

**Issue by yuno2k** [djhaled/Uiana-MapImporter#6]
I tried to import a map into UE using Uiana, but it crashes the moment meshes import starts.
any solutions?
![Desktop Screenshot 2023 03 26 - 08 15 51 25](https://user-images.githubusercontent.com/128949702/227753632-b9f3eb7d-df54-49b0-83ad-f631b3f65789.png)

**Comment by djhaled** [comment]
need more info on that but might have to do with your pc language?
