### ISSUE TITLE
UE5.2 Compilation Error

### ISSUE THREAD

**Issue by TrueXPixells** [djhaled/Uiana-MapImporter#8]
Hi! i using ue5.2 and downloaded from main branch zip file (not releases also no publish after january) here is logs files; I hope it will be resolved ASAP

[1/9] Compile [x64] Module.Uiana.cpp
[2/9] Resource Default.rc2
[3/9] Resource Default.rc2
[4/9] Compile [x64] Module.UnrealPSKPSA.cpp
D:\ProjectT\Plugins\UnrealPSKPSA\Source\UnrealPSKPSA\Private\BPFL.cpp(235): warning C4996: 'CreatePackage': Use CreatePackage overload that does not take the first Outer parameter. Specifying non-null outers for UPackages is no longer supported. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\ProjectT\Plugins\UnrealPSKPSA\Source\UnrealPSKPSA\Private\PSAFactory.cpp(31): warning C4996: 'IAnimationDataController::SetPlayLength': SetPlayLength with length in seconds in deprecated use SetNumberOfFrames using FFrameNumber instead Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\ProjectT\Plugins\UnrealPSKPSA\Source\UnrealPSKPSA\Private\PSAFactory.cpp(55): warning C4996: 'IAnimationDataController::AddBoneTrack': AddBoneTrack returning index is deprecated use AddBoneCurve returning bool instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
D:\ProjectT\Plugins\UnrealPSKPSA\Source\UnrealPSKPSA\Private\PSKFactory.cpp(162): error C2027: use of undefined type 'FSkeletalMeshLODInfo'
D:\UE_5.2\Engine\Source\Runtime\Engine\Classes\Engine\SkinnedAsset.h(24): note: see declaration of 'FSkeletalMeshLODInfo'
D:\ProjectT\Plugins\UnrealPSKPSA\Source\UnrealPSKPSA\Private\PSKFactory.cpp(163): error C2027: use of undefined type 'FSkeletalMeshLODInfo'
D:\UE_5.2\Engine\Source\Runtime\Engine\Classes\Engine\SkinnedAsset.h(24): note: see declaration of 'FSkeletalMeshLODInfo'
D:\ProjectT\Plugins\UnrealPSKPSA\Source\UnrealPSKPSA\Private\PSKFactory.cpp(164): error C2027: use of undefined type 'FSkeletalMeshLODInfo'
D:\UE_5.2\Engine\Source\Runtime\Engine\Classes\Engine\SkinnedAsset.h(24): note: see declaration of 'FSkeletalMeshLODInfo'
D:\ProjectT\Plugins\UnrealPSKPSA\Source\UnrealPSKPSA\Private\PSKFactory.cpp(165): error C2027: use of undefined type 'FSkeletalMeshLODInfo'
D:\UE_5.2\Engine\Source\Runtime\Engine\Classes\Engine\SkinnedAsset.h(24): note: see declaration of 'FSkeletalMeshLODInfo'
D:\ProjectT\Plugins\UnrealPSKPSA\Source\UnrealPSKPSA\Private\PSKFactory.cpp(166): error C2027: use of undefined type 'FSkeletalMeshLODInfo'
D:\UE_5.2\Engine\Source\Runtime\Engine\Classes\Engine\SkinnedAsset.h(24): note: see declaration of 'FSkeletalMeshLODInfo'
D:\ProjectT\Plugins\UnrealPSKPSA\Source\UnrealPSKPSA\Private\PSKFactory.cpp(179): error C2027: use of undefined type 'FSkeletalMeshLODInfo'
D:\UE_5.2\Engine\Source\Runtime\Engine\Classes\Engine\SkinnedAsset.h(24): note: see declaration of 'FSkeletalMeshLODInfo'
D:\ProjectT\Plugins\UnrealPSKPSA\Source\UnrealPSKPSA\Private\PSKFactory.cpp(192): error C2027: use of undefined type 'FSkeletalMaterial'
D:\UE_5.2\Engine\Source\Editor\UnrealEd\Public\ImportUtils\SkeletalMeshImportUtils.h(10): note: see declaration of 'FSkeletalMaterial'
[5/9] Link [x64] UnrealEditor-UnrealPSKPSA.lib cancelled
[6/9] Link [x64] UnrealEditor-UnrealPSKPSA.dll cancelled
[7/9] Link [x64] UnrealEditor-Uiana.lib
   Creating library D:\ProjectT\Plugins\Uiana\Intermediate\Build\Win64\x64\UnrealEditor\Development\Uiana\UnrealEditor-Uiana.lib and object D:\ProjectT\Plugins\Uiana\Intermediate\Build\Win64\x64\UnrealEditor\Development\Uiana\UnrealEditor-Uiana.exp
[8/9] Link [x64] UnrealEditor-Uiana.dll
   Creating library D:\ProjectT\Plugins\Uiana\Intermediate\Build\Win64\x64\UnrealEditor\Development\Uiana\UnrealEditor-Uiana.suppressed.lib and object D:\ProjectT\Plugins\Uiana\Intermediate\Build\Win64\x64\UnrealEditor\Development\Uiana\UnrealEditor-Uiana.suppressed.exp
[9/9] WriteMetadata UnrealEditor.target cancelled

**Comment by KaiserM21** [comment]
![works](https://github.com/djhaled/Uiana-MapImporter/assets/106357974/cd06e844-9222-452c-a86a-1a4c5c02d12a)
I have uploaded a fix for compile errors last week already. The plugin performance itself has not been fully tested yet, so I have not made a release.
